### ISSUE TITLE
dirent.h is not found

### ISSUE THREAD

**Issue by Archiatrus** [Cryptyc/Sc2LadderServer#122]
The dev branch (didn't test master) is not compiling under Windows because dirent.h is not found. I know it is in sc2util but the compiler does not find it. I also think it is suspicious that it is `#include "dirent.h"`. Shouldn't it be `#include "sc2util/dirent.h"`? (Also doesn't work.)

Could it be that you somehow have dirent.h installed on some standard path @Cryptyc ? What happens if you say open file in your IDE? Does it really do into the s2client-api directory?

**Comment by alkurbatov** [comment]
Have you launched cmake before compilation? 
If you dud, have you cleaned up cmake cache before launch?

**Comment by Archiatrus** [comment]
CMake yes, clean up no. Good point.

**Comment by alkurbatov** [comment]
>Shouldn't it be #include "sc2util/dirent.h"? 

It shouldn't, because `sc2util/dirent.h` is pure Windows and Linux systems already has direct.h.

**Comment by Archiatrus** [comment]
How does the s2client-api handle that when you compile it on Linux? I will look it up.

**Comment by alkurbatov** [comment]
Yes, @Cryptyc used the similar approach and we got broken unix builds.Thats why we search for direct.h in CMake.

**Comment by Archiatrus** [comment]
I removed the build folder and tried to build again. It failed again with
```
c:\users\d\desktop\sc2 ai\sc2ladderserver-exe\src\sc2laddercore\toolscommon.cpp(6): fatal error C1083: Cannot open include file: 'dirent.h': No such file or directory
```

**Comment by alkurbatov** [comment]
Hm. I thought @Cryptyc checked compilation before merging that PR.
@Cryptyc ?

**Comment by Cryptyc** [comment]
yeh, sorry it seems to work for me, I'l check it out with a fresh install though

**Comment by alkurbatov** [comment]
@Archiatrus 
I think that's because this line has a typo
https://github.com/Cryptyc/Sc2LadderServer/blob/master/src/CMakeLists.txt#L15

Try to change it to:
```cmake
if (WIN32)
    include_directories(SYSTEM
        ${PROJECT_SOURCE_DIR}/s2client-api/src/sc2utils
    )
endif ()
```

**Comment by Archiatrus** [comment]
That fixed the problem. I leave this open until a PR fixing this is merged.

**Comment by alkurbatov** [comment]
Ok, I'll prepare a PR at weekends, if it will not be fixed earlier.

**Comment by Cryptyc** [comment]
This should be fixed now
