### ISSUE TITLE
How can I handle this situation?

### ISSUE THREAD

**Issue by WanChuang1995** [Cryptyc/Sc2LadderServer#142]
12-06-2019 10-25-06: LadderManager started.
12-06-2019 10-25-06: Found agents:
12-06-2019 10-25-06: * MyBot
12-06-2019 10-25-06: * MyBot1
12-06-2019 10-25-06: Found the following maps:
12-06-2019 10-25-06: * CatalystLE.SC2Map
12-06-2019 10-25-06: Creating match: MyBot vs MyBot1 on CatalystLE.SC2Map
12-06-2019 10-25-06: MatchupList loaded from file with 1 matches to go.
12-06-2019 10-25-06: Initialization finished.

12-06-2019 10-25-06: Starting MyBot vs MyBot1 on CatalystLE.SC2Map
12-06-2019 10-25-06: Starting the StarCraft II clients.
12-06-2019 10-25-19: MyBot : Client changed status from unknown to launched
12-06-2019 10-25-19: MyBot1 : Client changed status from unknown to launched
12-06-2019 10-25-19: Creating the game on CatalystLE.SC2Map.
12-06-2019 10-25-19: MyBot : Client changed status from launched to init_game
12-06-2019 10-25-19: Starting the bots MyBot and MyBot1.
12-06-2019 10-25-19: Starting bot: MyBot with command:S:/anaconda/envs/SC2/python.exe run.py --GamePort 5677 --StartPort 5690 --LadderServer 127.0.0.1 --OpponentId b36bc7ce94edc67
12-06-2019 10-25-21: Starting bot: MyBot1 with command:S:/anaconda/envs/SC2/python.exe run.py --GamePort 5678 --StartPort 5690 --LadderServer 127.0.0.1 --OpponentId 93e41c6e20911b9
12-06-2019 10-25-23: Starting the match.
12-06-2019 10-25-23: Starting proxy for MyBot
12-06-2019 10-25-23: Starting proxy for MyBot1
12-06-2019 10-27-03: MyBot1 : Waiting for a response had a timeout or was invalid.
12-06-2019 10-27-57: MyBot : Waiting for a response had a timeout or was invalid.
12-06-2019 10-27-57: MyBot1 : Exiting with Error Average step time -nan(ind) microseconds, total time: 0 seconds, game loops: 0
12-06-2019 10-27-57: MyBot : Exiting with Error Average step time -nan(ind) microseconds, total time: 0 seconds, game loops: 0
12-06-2019 10-27-58: MyBot : Match ended in error. Can not save replay.
12-06-2019 10-27-58: MyBot1 : Match ended in error. Can not save replay.
12-06-2019 10-27-58: Saving replay failed.

**Comment by Cryptyc** [comment]
I'm not sure from the log.  It seems like the bot is failing to send the correct startgame request.   Its possible that this is a Blizzard bug that was introduced with the 4.9 client.  Is this what you are using.  Also can you confirm that both sc2 clients have been started?

**Comment by WanChuang1995** [comment]
Just use sc2 version=4.8.4
