### ISSUE TITLE
LadderManager crashes without error message

### ISSUE THREAD

**Issue by SimonPrins** [Cryptyc/Sc2LadderServer#16]
I have a problem getting the LadderManager to work.
I compiled it on my own machine. I also edited in pull request #15 which fixed a different crash I encountered.
I am trying to run a match between 5minBot and tscmoo.
Two Starcraft instances start, but they remain black and don't load the map.
Two new prompts pop up, one for each bot.
After a while the LadderManager crashes and a window pops up with the message 'LadderManager.exe has stopped working'.
No error message is written to the console for the LadderManager.

A short time later both bots crash as well. They bot get a window with '<botname>.exe has stopped working'. They do both log an error message: 
'Assertion failed: pi_.process_id, file C:\Users\D\Desktop\SC2 AI\s2client-api\src\sc2api\sc2_client.cc, line 1825' for 5minBot and 'Assertion failed: pi_.process_id, file X:\c++\s2client-api\src\sc2api\sc2_client.cc, line 1825' for tscmoo.

Full output for the LadderManager:
```
LadderManager started.
Starting with 1 maps:
* InterloperLE.SC2Map
Starting with agents:
5minBot
Computer
CryptBot
FradBot
HjaxAI
Tyr
tscmoo
Creating match: 5minBot vs tscmoo on InterloperLE.SC2Map
MatchupList loaded from file with 1 matches to go.
Starting 5minBot vs tscmoo on InterloperLE.SC2Map
Connected...
Connected...
Sending: create_game {
  local_map {
    map_path: "InterloperLE.SC2Map"
  }
  player_setup {
    type: Participant
    race: Terran
    difficulty: Easy
  }
  player_setup {
    type: Participant
    race: Protoss
    difficulty: Easy
  }
  realtime: false
}
Waiting for response...
Recieved create game response
Bot started.
Bot started.
Starting proxy

Starting proxy

Waiting for response...
Waiting for response...
Waiting for response...
Waiting for response...
```

full output for 5minBot.exe:
```
--GamePort is an unrecognized argument.
Connecting to port 5677

Connected to 127.0.0.1:5677
Waiting for the JoinGame response.
Assertion failed: pi_.process_id, file C:\Users\D\Desktop\SC2 AI\s2client-api\src\sc2api\sc2_client.cc, line 1825
```

full output for tscmoo.exe:
```
--LadderServer is an unrecognized argument.
00000: connecting to port 5678

Connected to 127.0.0.1:5678
Waiting for the JoinGame response.
Assertion failed: pi_.process_id, file X:\c++\s2client-api\src\sc2api\sc2_client.cc, line 1825
```

**Comment by Cryptyc** [comment]
Ok, I'll take a look thanks

**Comment by Cryptyc** [comment]
I think I managed to reproduce the problem.  It seems to be an issue in the way sc2 starts up.  I'm looking into it.  I think it might be something in the sc2 config

**Comment by SimonPrins** [comment]
I have tried deleting the Variables.txt file and starting SC2 again to recreate it. This has actually worked once and I was able to play a game with the ladder manager. The next time, however, it didn't work anymore, even after deleting the Variables.txt file again. 

I suspect the problem is actually with the Starcraft 2 client itself, so I will close this issue.
