### ISSUE TITLE
Bot does not get a chance to receive and handle the result of the game.

### ISSUE THREAD

**Issue by SimonPrins** [Cryptyc/Sc2LadderServer#23]
When a bot requests an observation after the game has ended, the Starcraft 2 client sends a final Observation response, with status 'Ended'. The PlayerResult field will tell you which bot won or lost. This works fine for my bot when I run it in single player mode vs the Blizzard AI, but when I use it with the LadderManager I never receive the response. 

I suspect that either the Starcraft 2 client, or the bot instance is closed before the game results are sent.

**Comment by lladdy** [comment]
@SimonPrins @Cryptyc 
Is this still an issue?

**Comment by NikEyX** [comment]
Yes, still an issue

**Comment by Cryptyc** [comment]
This should be fixed with latest changes, any more problems, let me know
