### ISSUE TITLE
Bots should operate in their working directory

### ISSUE THREAD

**Issue by NikEyX** [Cryptyc/Sc2LadderServer#27]
Right now the bots are launched from the ladder managers' working directory, which results in my bot creating all kind of files in the root. For safety and for easy of use, it would make sense to launch bots from within their own working directories (without access to anything else).

**Comment by alkurbatov** [comment]
Hi, @NikEyX .
This issue will be fixed after merge of #21. A separate 'build' directory will be used to compile and run the server.

**Comment by alkurbatov** [comment]
No, I am wrong here. You are speaking about bots, not the server.
Regarding the bots we have #25 already merged.

**Comment by Cryptyc** [comment]
This will be implemented for the next version

**Comment by lladdy** [comment]
@Cryptyc does this mean it's already done?
Is it worth me looking into?

**Comment by Cryptyc** [comment]
its something thats basicly done, I just need to clean things up and get it in the repo

**Comment by lladdy** [comment]
All good then :)

**Comment by Archiatrus** [comment]
Working directory was introduced in fcbff6a6b73d2522308f5177570b8e698bbfe361
I wrote a seperate issue for the security concerns #33

**Comment by lladdy** [comment]
I think we can.
