### ISSUE TITLE
Consolidate configuration files

### ISSUE THREAD

**Issue by NikEyX** [Cryptyc/Sc2LadderServer#28]
I think it would be a lot better if the users wouldn't need to worry about 5 different config files, some of them even being in different directories.

How about a single (or maybe a max of 2) JSON files that contain all relevant config settings?

Also, please add file extensions, e.g. bots.cfg - disregarding file extensions comes at the detriment of windows users (unless they use NotePad++, but that's not a good default).

**Comment by lladdy** [comment]
I'm in support of this.
Seeing as we have json support, it might not take much to merge LadderBots.json, LadderManager.conf and maplist into 1 json file

**Comment by alkurbatov** [comment]
People tend to split thing into smaller and easy-to-manage parts and here you request to create a 'super' config ;)

Thats really a matter of taste. I would say that we can join maps pool and bots config but even current situation looks good.

>Also, please add file extensions, e.g. bots.cfg -
Which can cause loss of syntax highlight support in some IDEs and text editors. Does it really worth?
Don't forget that the server is going to be cross platform i.e. for users of other platforms too.

**Comment by Cryptyc** [comment]
I think maybe we can merge the maplist and the ladderbots config file into an instance config, and still keep the main settings config file, as we current have.  This way there is a clear distinction.  The matchup list should never be contained in a config file as it is auto generated.

**Comment by lladdy** [comment]
> into an instance config
@Cryptyc I'm not sure what you mean by this?

**Comment by Cryptyc** [comment]
I have merged the maplist and ladderbots.json file into a single file in #41ab8acd20875e3883840f2e7aba10d059d0d0d3  I think this makes our current situation pretty good, so closing this issue
