### ISSUE TITLE
Allow to disable replays upload

### ISSUE THREAD

**Issue by alkurbatov** [Cryptyc/Sc2LadderServer#31]
Usually we need to upload replays only after real ladder games, thus this functionality is not needed in testing and bot creator's experiments. 
Lets allow to disable replays upload via a dedicated cmake variable, e.g. UPLOAD_REPLAY:BOOL.

**Comment by alkurbatov** [comment]
The only question is should the replays upload be enabled or disabled by default.

**Comment by Cryptyc** [comment]
This has been fixed in latest commit
