### ISSUE TITLE
Proposal: Kill-Timer

### ISSUE THREAD

**Issue by m1ndgames** [Cryptyc/Sc2LadderServer#36]
I propose to implement a kill-timer that ends the match (with a draw) after some time (5m?) without any kill has passed.

What do you think?

**Comment by lladdy** [comment]
This isn't a bad idea. I think it depends on how many "micromachine walking into a wall for 5 minutes" replays we get.

Currently it appears that this was already planned for implementation - there's "MaxGameTime" configuration setting in the LadderManager.conf file.

Otherwise, an alternative might be to simply rely on the in-built SC2 draw timer. I believe the in-built timer is also extended by other actions as well though, such as mining minerals.

**Comment by Cryptyc** [comment]
Currently we have the built in draw timer, and the max game timer, which just times out the match after 45mins.  It would be possible to implement a kill timer, but would take a bit of hacking around with the observation responses.

While this would be good, I think its fairly low priority at the moment, but if I get some time after the rest of the bugs have been fixed, I'll take a look

**Comment by m1ndgames** [comment]
To give an Example, check this Replay: http://107.161.27.148/replay/4raxBotvHJaxAI-OdysseyLE.Sc2Replay

Both AIs are kinda flawed. Zerg is not attacking and Terran is not looking for other bases. After 12 minutes nothing happens anymore. Using a timer that checks for kills could be a solution to pass those games quicker. (on the ladderserver and while replaying)

btw.: sscait has it aswell, I dont know their reasons tho.

> Edit: Just a thought: If the problem is more that it's boring to watch the replays, maybe we could improve the observer instead to speed past those parts?

I would like to be able to stream in realtime in the future (to play game sound), so using the observer to skip time would not be my preferred solution.

**Comment by Archiatrus** [comment]
I would say it is very hard to find a good threshold. My bot is very passive in the beginning. If it would play against itself it would easily reach 5 min without a kill.

**Comment by m1ndgames** [comment]
Yep, how about the kill timer starts after 5 minutes to allow "turtles" to set up the base

**Comment by lladdy** [comment]
> so using the observer to skip time would not be my preferred solution.

If you're still using the observer that @Archiatrus wrote at the time, then I figure we'd only need to control the step rate?

As I see it, the win condition for Sc2 is already well defined within the game. Correct me if I'm wrong, but I see this as more of an issue of observing the replays afterwards, which I would hope the Observer can be adapted to cater for? (Does running the game in real-time not allow control over the speed?)
If not, maybe a kill-timer _is_ the answer.

**Comment by m1ndgames** [comment]
> Correct me if I'm wrong, but I see this as more of an issue of observing the replays afterwards
Totally, for the ladder it makes no difference ;)
