### ISSUE TITLE
Basic scripts to generate matchuplist

### ISSUE THREAD

**Issue by Archiatrus** [Cryptyc/Sc2LadderServer#41]
Would nice if also a basic script is included that can create certain types of matchup lists. Like if you want to test your bot against all other available bots on all available maps. Or round robin bo1. Or...

**Comment by lladdy** [comment]
This sounds useful.
Would you do it as a standalone/disconnected ability? or just have it as an optional pre-step to running the ladder? Of course both is an option as well:
```
// just runs the ladder
Sc2LadderServer.exe --Run

// just generates a matchuplist
Sc2LadderServer.exe --MatchupGenType RoundRobin

// runs ladder after generating the list
Sc2LadderServer.exe --Run --MatchupGenType RoundRobin
```
This could be used in future with website integration as well:
```
// runs ladder after getting a matchuplist from the website
Sc2LadderServer.exe --Run --MatchupGenType Website
```

**Comment by Archiatrus** [comment]
I think I would separate it. More intuitive for the user. Not everyone is used to command line etc.

**Comment by alkurbatov** [comment]
I believe we should the runtime modes according to the usage scenarious. Right now we have at least 3:
a. A developer runs 1vs1 match (no matchup list really needed).
b. @Cryptyc runs the ladder (specific way to generate the list).
c. Others run their own tournaments (different matchup lusts abd ways to generate it).

If we could simplify #a (e.g. no list) and provide a tools to generate the list begore the start of the ladder (looks more useful for #c) it would be really nice.

**Comment by Archiatrus** [comment]
I disagree with a. and "no matchup list really needed". I would imagine something like this would be useful:

- My bot: Abot
- Opponents: Bbot, Cbot, DBot
- Maps: X,Y,Z
- Optional: repeat t times

And then it generates a list with Abot vs each of the other bots on each map.

I think b is basically covered already. If you do not provide a matchuplist file it generates round robin on all maps. But it would maybe be nice if it saves this list.

**Comment by alkurbatov** [comment]
This true when you need a complex test (e.g. before release), but what if you just try to beat a specific opponent again and again?

I think, the match up list generation should be moved out of the ladder server into the scripts (ideally python scripts to support crissplatform by default). So the workflow would be:
1. Generate a match up list with one of the existing scripts or your own.
2. Check it manually if needed.
3. Start the ladder manager.

**Comment by Archiatrus** [comment]
Yeah totally agree with this workflow. That is what I meant with "separated". And yes, it can be very useful to quickly(!) generate this complex test a few hours before the submission deadline ;)

**Comment by Cryptyc** [comment]
Definately a good idea, I may try to have a look at doing something tonight if I get some time

**Comment by Archiatrus** [comment]
Hjax (?) already had a basic one yesterday. Maybe he is bored ;)

**Comment by m1ndgames** [comment]
just reading this... i use a small script to generate a list of matches against all enemies on all maps:
https://gist.github.com/m1ndgames/b69dded852916138b910ff4e45cbbc6c

its perl tho ^^

**Comment by NikEyX** [comment]
Personally I'd love to have a GUI for that. Using something like QTDesigner might be the easiest. It would make usage a lot nicer - especially since we have had a large inflow of new people it would help tremendously to give them easy-to-use tools. I agree with Arch that command line isn't for everyone and I think we need to make it as easy as possible for people to use

**Comment by Archiatrus** [comment]
Resolved for me with the ladderGUI.

https://github.com/NikEyX/LadderGUI
