### ISSUE TITLE
Commit a5efd2a8550e3f6befa05b8ad8506e187f32afe5 broke relative path support.

### ISSUE THREAD

**Issue by Archiatrus** [Cryptyc/Sc2LadderServer#42]
The commit a5efd2a8550e3f6befa05b8ad8506e187f32afe5 broke relative path support.

The root path is not needed because you actually start python.exe. And you give it rootpath as working directory [here](https://github.com/Cryptyc/Sc2LadderServer/blob/master/src/ToolsWindows.cpp#L46). So the bot file is from the perspective of python.exe located at .

**Comment by Cryptyc** [comment]
Fixed in commit f5688a40d1153ead8122673b5aac8efbe6b8e3bd
