### ISSUE TITLE
Add a flag to also catch stdout

### ISSUE THREAD

**Issue by Archiatrus** [Cryptyc/Sc2LadderServer#43]
Yesterday we struggled to get the python-sc2 bots to run with the laddermanager. In the end it turned out that the sc2 executable path was hard coded in python-sc2. This would have been easy to fix but the problem was that the "executable not found" error was sent to stdout. And the bot window closed so fast that you could not read it. The error log stayed empty.

That is why I propose a --debug flag that enables the laddermanager to also write stdout of the bots to file. So a small change [here](https://github.com/Cryptyc/Sc2LadderServer/blob/master/src/ToolsWindows.cpp#L37). I know that in the end it would be the responsibility of the person maintaining the API to use a proper way to message errors. But I think we can not assume that this always happens. Of course the --debug flag would not be used for normal ladder play.

**Comment by alkurbatov** [comment]
Implemented for Unix, Windows part still requires implementation.

**Comment by Archiatrus** [comment]
Already implemented with the debug field in the bot json.
