### ISSUE TITLE
Write results (win/loss) to text or json file

### ISSUE THREAD

**Issue by BurnySc2** [Cryptyc/Sc2LadderServer#48]
Please have the LadderServer save results to a text or json file.

Most importantly is which bot won, but other optional useful information (for bot debugging) could be:
- matchup
- game duration
- resources (bank) at the end of the game of both players
- supply / max supply at the end of the game of the winning player
- time supply blocked

**Comment by Cryptyc** [comment]
Sounds like a good idea, I can start on this next week.  Basic info such as win/loss and game duration should be easy, might be take a bit more time for some of the more complex info

**Comment by Cryptyc** [comment]
This has been implemented in c2c8d1cfe60f684d90eae23da509bd2e8b17da50
