### ISSUE TITLE
Setting `EnablePlayerIds(true)` in the constructor ends the execution almost immediately

### ISSUE THREAD

**Issue by Archiatrus** [Cryptyc/Sc2LadderServer#53]
title

**Comment by Cryptyc** [comment]
I'll take a look at this tonight

**Comment by Cryptyc** [comment]
Setting PlayerIdFile variable in config is a workaround for this.  I will work on a proper fix

**Comment by Cryptyc** [comment]
@Archiatrus I haven't been able to reproduce this, can you send me your config file to check?

**Comment by Archiatrus** [comment]
I am not at home right now. But the config was the normal one that just missed the playeridfile field.

**Comment by Archiatrus** [comment]
In the end the solution was using an up to date config file, i.e., one that has a player id file field.
