### ISSUE TITLE
[linux] python is launched in botdirectory - file not found

### ISSUE THREAD

**Issue by m1ndgames** [Cryptyc/Sc2LadderServer#63]
applies to linux only:
currently the ladderserver tries to launch python locally in the bot directory and fails.

if execv in [ToolsUnix.cpp](https://github.com/Cryptyc/Sc2LadderServer/blob/master/src/sc2laddercore/ToolsUnix.cpp#L58) is replaced with execvp the python path should be available. (untested)

**Comment by alkurbatov** [comment]
Fixed.

**Comment by m1ndgames** [comment]
verified
