### ISSUE TITLE
python naming differences

### ISSUE THREAD

**Issue by m1ndgames** [Cryptyc/Sc2LadderServer#64]
on linux the command "python" points to python v2 and "python3" to v3. the ladderserver currently runs "python" while python-sc2 needs python >v3.6.

on debian and ubuntu which are the most used desktop linux os, "python3" points to python v3.5.
if you install python v3.6, you will need to call "python3.6".

On windows it depends how python is installed as anaconda might call python v3.6 while an installation via cygwin will use python2 by default.

to solve all this mess, i suggest to add a config file entry 

> python=python3.6

and make it configurable

**Comment by alkurbatov** [comment]
Probably that should b3 set per bot (i.e. in the bots config) as we could have pysc2 bots too.

**Comment by m1ndgames** [comment]
Could we make it mandatory to use python3.6 on the ladder? (The version is needed for python-sc2, while pysc2 can still be used with 3.6)

**Comment by m1ndgames** [comment]
https://github.com/Cryptyc/Sc2LadderServer/commit/c9f352ed9a30a82b3e4067f4e4fdc215afdee88d
