### ISSUE TITLE
LocalReplayDirectory is invalid without a trailing slash.

### ISSUE THREAD

**Issue by lladdy** [Cryptyc/Sc2LadderServer#75]
As per https://github.com/Cryptyc/Sc2LadderServer/pull/74#discussion_r208117752

The LocalReplayDirectory setting in the LadderManager configuration is invalid if it doesn't have a trailing slash.
This ideally should be resolved so that it can be validly handled without said trailing slash.

**Comment by Archiatrus** [comment]
Shouldn't be a problem anymore: https://github.com/Cryptyc/Sc2LadderServer/blob/Dev/src/sc2laddercore/LadderGame.cpp#L130-L133

**Comment by lladdy** [comment]
Thanks @Archiatrus.
