### ISSUE TITLE
Support for java bots.

### ISSUE THREAD

**Issue by ocraft** [Cryptyc/Sc2LadderServer#80]
Please add the support for java bots written with https://github.com/ocraft/ocraft-s2client. The command that should be used to run the bot:

java -jar BOT.jar // e.g. java -jar ocraft-bot.jar --GamePort 5000 --StartPort 5050

Java should be in the version 1.9 or higher.
Bot sample prepared for the ladder: https://github.com/ocraft/ocraft-s2client/blob/master/ocraft-s2client-sample/src/main/java/com/github/ocraft/s2client/sample/SampleLadderBot.java

**Comment by Cryptyc** [comment]
Added in c9c96674db16036ceab820790eb23ffd6f7d1cbb
