### ISSUE TITLE
Compile errors building Sc2LadderServer on OSX

### ISSUE THREAD

**Issue by ericbroda** [Cryptyc/Sc2LadderServer#93]
I am using OSX (MacOS, High Sierra, 10.13.6) and am getting the following error when building Sc2LadderServer.  Any help is appreciated.

Followed instructions and tried command:  make Sc2LadderServer.

Much of the code built (with lots of warnings) but the following error stopped the build:

Building C object s2client-api/contrib/civetweb/src/CMakeFiles/civetweb-c-library.dir/civetweb.c.o
[working-dir]/Sc2LadderServer/s2client-api/contrib/civetweb/src/civetweb.c:32:9: warning: macro name is a reserved identifier
      [-Wreserved-id-macro]
#define _GNU_SOURCE /* for setgroups() */
        ^
[working-dir]/Sc2LadderServer/s2client-api/contrib/civetweb/src/civetweb.c:38:9: warning: macro name is a reserved identifier
      [-Wreserved-id-macro]
#define _LARGEFILE_SOURCE /* For fseeko(), ftello() */
        ^
[working-dir]/Sc2LadderServer/s2client-api/contrib/civetweb/src/civetweb.c:41:9: warning: macro name is a reserved identifier
      [-Wreserved-id-macro]
#define _FILE_OFFSET_BITS 64 /* Use 64-bit file offsets by default */
        ^
[working-dir]/Sc2LadderServer/s2client-api/contrib/civetweb/src/civetweb.c:44:9: warning: macro name is a reserved identifier
      [-Wreserved-id-macro]
#define __STDC_FORMAT_MACROS /* <inttypes.h> wants this for C++ */
        ^
[working-dir]/Sc2LadderServer/s2client-api/contrib/civetweb/src/civetweb.c:47:9: warning: macro name is a reserved identifier
      [-Wreserved-id-macro]
#define __STDC_LIMIT_MACROS /* C++ wants that for INT64_MAX */
        ^
[working-dir]/python/Sc2LadderServer/s2client-api/contrib/civetweb/src/civetweb.c:1556:9: warning: macro name is a reserved identifier
      [-Wreserved-id-macro]
#define _DARWIN_UNLIMITED_SELECT
        ^
[working-dir]/Sc2LadderServer/s2client-api/contrib/civetweb/src/civetweb.c:5725:17: warning: implicit conversion loses integer precision:
      'long' to '__darwin_suseconds_t' (aka 'int') [-Wshorten-64-to-32]
                        tv.tv_usec = (long)((ms_wait % 1000) * 1000);
                                   ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[working-dir]/Sc2LadderServer/s2client-api/contrib/civetweb/src/civetweb.c:17867:32: error: unknown warning group '-Werror', ignored
      [-Werror,-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Werror"
                               ^
7 warnings and 1 error generated.
make[3]: *** [s2client-api/contrib/civetweb/src/CMakeFiles/civetweb-c-library.dir/civetweb.c.o] Error 1
make[2]: *** [s2client-api/contrib/civetweb/src/CMakeFiles/civetweb-c-library.dir/all] Error 2
make[1]: *** [src/CMakeFiles/Sc2LadderServer.dir/rule] Error 2
make: *** [Sc2LadderServer] Error 2

**Comment by alkurbatov** [comment]
Hi @ericbroda 
This is the sc2API issue, see https://github.com/Blizzard/s2client-api/issues/239

**Comment by ericbroda** [comment]
I fixed the civetweb issue (as per #239 referenced above) and now received the following error:

[ 96%] Building CXX object src/CMakeFiles/Sc2LadderCore.dir/sc2laddercore/AgentsConfig.cpp.o
[working-dir]/Sc2LadderServer/src/sc2laddercore/AgentsConfig.cpp:8:10: fatal error: 'filesystem' file not found
#include <filesystem>
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [src/CMakeFiles/Sc2LadderCore.dir/sc2laddercore/AgentsConfig.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/Sc2LadderCore.dir/all] Error 2
make: *** [all] Error 2

It appears that XCode does not have <filesystem> ... continuing to investigate...

**Comment by alkurbatov** [comment]
This is broken by @Cryptyc 
You should either comment this functionality, or install gcc6 e.g. using homebrew.

**Comment by ericbroda** [comment]
I installed gcc6 (using homebrew) as well as other gcc/g++ versions and the builds (each version) broke at the same point.  OSX support for "filesystem" is not very complete, it appears.

Any other ideas?

**Comment by ericbroda** [comment]
Here is the latest set of compile errors:

```
Building CXX object s2client-api/src/CMakeFiles/sc2utils.dir/sc2utils/sc2_manage_process.cc.o
In file included from /System/Library/Frameworks/CoreGraphics.framework/Headers/CGContext.h:21:0,
                 from /System/Library/Frameworks/CoreGraphics.framework/Headers/CGBitmapContext.h:9,
                 from /System/Library/Frameworks/CoreGraphics.framework/Headers/CoreGraphics.h:11,
                 from /System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:35,
                 from /System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:24,
                 from /Users/ericbroda/Development/python/Sc2LadderServer/s2client-api/src/sc2utils/sc2_manage_process.cc:41:
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGPath.h:391:15: error: expected unqualified-id before '^' token
 typedef void (^CGPathApplyBlock)(const CGPathElement * element);
               ^
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGPath.h:391:15: error: expected ')' before '^' token
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGPath.h:393:53: error: 'CGPathApplyBlock' has not been declared
 CG_EXTERN void CGPathApplyWithBlock(CGPathRef path, CGPathApplyBlock CF_NOESCAPE block)
                                                     ^~~~~~~~~~~~~~~~
/Users/ericbroda/Development/python/Sc2LadderServer/s2client-api/src/sc2utils/sc2_manage_process.cc: In function 'void sc2::GetDirectory(std::__cxx11::string&, uint32_t, short int)':
/Users/ericbroda/Development/python/Sc2LadderServer/s2client-api/src/sc2utils/sc2_manage_process.cc:304:17: warning: 'OSErr FSFindFolder(FSVolumeRefNum, OSType, Boolean, FSRef*)' is deprecated [-Wdeprecated-declarations]
     OSErr err = FSFindFolder(domain, folderType, false, &fsref);
                 ^~~~~~~~~~~~
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:176:0,
                 from /System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20,
                 from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23,
                 from /System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:20,
                 from /Users/ericbroda/Development/python/Sc2LadderServer/s2client-api/src/sc2utils/sc2_manage_process.cc:41:
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Folders.h:286:1: note: declared here
 FSFindFolder(
 ^~~~~~~~~~~~
/Users/ericbroda/Development/python/Sc2LadderServer/s2client-api/src/sc2utils/sc2_manage_process.cc:304:63: warning: 'OSErr FSFindFolder(FSVolumeRefNum, OSType, Boolean, FSRef*)' is deprecated [-Wdeprecated-declarations]
     OSErr err = FSFindFolder(domain, folderType, false, &fsref);
                                                               ^
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:176:0,
                 from /System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20,
                 from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23,
                 from /System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:20,
                 from /Users/ericbroda/Development/python/Sc2LadderServer/s2client-api/src/sc2utils/sc2_manage_process.cc:41:
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Folders.h:286:1: note: declared here
 FSFindFolder(
 ^~~~~~~~~~~~
/Users/ericbroda/Development/python/Sc2LadderServer/s2client-api/src/sc2utils/sc2_manage_process.cc:308:9: warning: 'OSStatus FSRefMakePath(const FSRef*, UInt8*, UInt32)' is deprecated [-Wdeprecated-declarations]
         FSRefMakePath(&fsref, reinterpret_cast<unsigned char*>(pathBuffer), PATH_MAX);
         ^~~~~~~~~~~~~
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Components.h:26:0,
                 from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:87,
                 from /System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20,
                 from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23,
                 from /System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:20,
                 from /Users/ericbroda/Development/python/Sc2LadderServer/s2client-api/src/sc2utils/sc2_manage_process.cc:41:
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Files.h:4086:18: note: declared here
 extern OSStatus  FSRefMakePath(const FSRef *ref, UInt8 *path, UInt32 pathBufferSize)     __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_8, __IPHONE_NA, __IPHONE_NA);
                  ^~~~~~~~~~~~~
/Users/ericbroda/Development/python/Sc2LadderServer/s2client-api/src/sc2utils/sc2_manage_process.cc:308:85: warning: 'OSStatus FSRefMakePath(const FSRef*, UInt8*, UInt32)' is deprecated [-Wdeprecated-declarations]
         FSRefMakePath(&fsref, reinterpret_cast<unsigned char*>(pathBuffer), PATH_MAX);
                                                                                     ^
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Components.h:26:0,
                 from /System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/CarbonCore.h:87,
                 from /System/Library/Frameworks/CoreServices.framework/Frameworks/AE.framework/Headers/AE.h:20,
                 from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:23,
                 from /System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:20,
                 from /Users/ericbroda/Development/python/Sc2LadderServer/s2client-api/src/sc2utils/sc2_manage_process.cc:41:
/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Files.h:4086:18: note: declared here
 extern OSStatus  FSRefMakePath(const FSRef *ref, UInt8 *path, UInt32 pathBufferSize)     __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_8, __IPHONE_NA, __IPHONE_NA);
                  ^~~~~~~~~~~~~
make[3]: *** [s2client-api/src/CMakeFiles/sc2utils.dir/sc2utils/sc2_manage_process.cc.o] Error 1
make[2]: *** [s2client-api/src/CMakeFiles/sc2utils.dir/all] Error 2
make[1]: *** [src/CMakeFiles/Sc2LadderServer.dir/rule] Error 2
make: *** [Sc2LadderServer] Error 2
```

**Comment by Cryptyc** [comment]
I probably need to put something in the tools to replace this, I'll do that after I got the new season running, should be this week, sorry about this.

**Comment by alkurbatov** [comment]
@ericbroda but as you can see here we have a different set of errors (again in the c++ API) which means that you should add some flags or do some fixes to make it work.
Perhaps lower version of gcc (e.g. 5th) would work, not sure. As far as I've head `filesystem` was added to gcc6, not sure about gcc5.

**Comment by alkurbatov** [comment]
@ericbroda Now compilation is fixed. Feel free to try :)

**Comment by Cryptyc** [comment]
Fixed
